### ISSUE TITLE
Can't use NULL in colClasses when select or drop is used as well.

### ISSUE THREAD

**Issue by DenaFrancis** [rethomics/damr#22]
Hi,
This is my code and the error that I get:
#Check data is correctly loaded
list.files(DATA_DIR, pattern= "*.txt|*csv")

#set working directory
setwd(DATA_DIR)

#Load metadata
metadata <- fread("metadata.csv")

#remove # to check if metadata is loaded correctly
metadata

#connect metadata to raw data
metadata <- link_dam_metadata(metadata, result_dir = DATA_DIR)
metadata

#loading data
dt <- load_dam(metadata)

Error in fread(path, col.names = col_names[which(DAM5_COLS != "_")], colClasses = col_class,  : 
  Can't use NULL in colClasses when select or drop is used as well.

I am not sure what it means and I am using the same template that I have been using in the past for the metadata. 

Thanks! I love this package by the way!

**Comment by qgeissmann** [comment]
Hi Dena,
Thanks for reporting your issue. Any chance you could upload your metadata and results so I can try to reproduce the issue on my system? :).  Thanks for your feedback on the package too!

**Comment by DenaFrancis** [comment]
Hi Quinton,
Seems that the issue was with my computer because everything ran smoothly on my laptop? I will try to upload the metadata nontheless. 
Thanks for your response!
Dena
