### ISSUE TITLE
load_dam column errors

### ISSUE THREAD

**Issue by jharv3y** [rethomics/damr#25]
Hi, sorry to post again.
I'm having problems with the load_dam and would really really appreciate any thoughts on what the issue could be, I just cant work it out.

When I try to use load_dam I get the following error;

> dt <- load_dam(metadata)
Error in fun(file, col.names = names(DAM5_COLS)[cols_to_keep], select = cols_to_keep) : 
  Column number 8 (select[4]) is too large for this table, which only has 7 columns.

I have no idea where this column is coming from, as I cant find any data set with an 8th column.

I've followed the code for DAM2, however have used my own metadata and data files.

> rm(list=ls())
> library(damr)
> library(zeitgebr)
> library(ggetho)
> library(behavr)
> library(data.table)
> DATA_DIR <- "C:\\Users\\jlhc\\Documents\\R\\fitboks"
> list.files(DATA_DIR, pattern= "*.txt|*.csv")
 [1] "bok_231.csv"        "bok_235.csv"        "bok_236.csv"        "bok_237.csv"       
 [5] "bok_263.csv"        "bok_267.csv"        "bok_269.csv"        "circadian_test.csv"
 [9] "metadata.csv"       "metadata_2.csv"    
> setwd(DATA_DIR)
> 
> metadata <- fread("metadata.csv")
> metadata
          file      start_datetime       stop_datetime  id
1: bok_231.csv 2019-03-12 15:51:00 2019-03-13 09:00:00 231
2: bok_235.csv 2019-03-13 16:00:00 2019-03-14 08:41:00 235
3: bok_236.csv 2019-03-08 15:53:00 2019-03-09 09:00:00 236
4: bok_237.csv 2019-03-11 15:51:00 2019-03-12 09:00:00 237
5: bok_263.csv 2019-03-13 16:00:00 2019-03-14 09:00:00 263
6: bok_267.csv 2019-03-06 15:49:00 2019-03-07 09:04:00 267
7: bok_269.csv 2019-03-14 13:58:00 2019-03-15 09:00:00 269
> 
> metadata <- link_dam_metadata(metadata, result_dir = DATA_DIR)
> metadata
> 
> 
> dt <- load_dam(metadata)
Error in fun(file, col.names = names(DAM5_COLS)[cols_to_keep], select = cols_to_keep) : 
  Column number 8 (select[4]) is too large for this table, which only has 7 columns.

Thank you so much again for any thoughts on this!!

Jess

**Comment by qgeissmann** [comment]
Hi Jess,
Sorry for a late reply! Did you make any progress? If not, could you upload your metadata and data so we can try to reproduce your issue :)?
Cheers!
Q

**Comment by jharv3y** [comment]
Ah no thank you so so much for taking the time to help!!! I'm sure it's an embarrassingly simple problem.
No luck yet, would really appreciate you taking a look. 
Thanks so much again!
Jess
(I tried changing the metadata input to a .txt, as dates were being weird if saved in .csv, heres the code with the correct file name)

DATA_DIR <- "C:\\Users\\jlhc\\Documents\\R\\fitboks"
list.files(DATA_DIR, pattern= "*.txt|*.csv")
setwd(DATA_DIR)

metadata <- fread("metadata_test.txt")
metadata

metadata <- link_dam_metadata(metadata, result_dir = DATA_DIR)
metadata


dt <- load_dam(metadata)

summary(dt)
[metadata_test.txt](https://github.com/rethomics/damr/files/3224695/metadata_test.txt)

[bok_231.txt](https://github.com/rethomics/damr/files/3224681/bok_231.txt)
[bok_269.txt](https://github.com/rethomics/damr/files/3224682/bok_269.txt)
[bok_235.txt](https://github.com/rethomics/damr/files/3224683/bok_235.txt)
[bok_236.txt](https://github.com/rethomics/damr/files/3224684/bok_236.txt)
[bok_237.txt](https://github.com/rethomics/damr/files/3224685/bok_237.txt)
[bok_263.txt](https://github.com/rethomics/damr/files/3224686/bok_263.txt)
[bok_267.txt](https://github.com/rethomics/damr/files/3224687/bok_267.txt)

**Comment by qgeissmann** [comment]
Hi @jharv3y, sorry for the late reply! It appears as though your data files are preprocessed already (i.e. they are showing the average activity per monitor instead of individual data). Did you use a tool to compute the average? damr will only take raw data file such as: https://github.com/rethomics/damr/blob/master/inst/extdata/M014.txt. I hope it helps!
