### ISSUE TITLE
Load_dam error help request

### ISSUE THREAD

**Issue by katenevin21** [rethomics/damr#36]
Hi, I am trying to use the rethomics system for the first time to analyze my DAM data. I am having an issue when trying to load the data and I was wondering if someone could possibly point out where I am going wrong? My code results in the error,
`Error in find_dam_first_last_lines(path, start_datetime, stop_datetime,  : 
  No data in selected date range`

**Here is my code attached below:**
library(damr)
DATA_DIR <- "C:/Users/Kate/OneDrive/Documents/R/23"
list.files(DATA_DIR, pattern= "*.txt|*.csv")
setwd(DATA_DIR)
metadata <- fread("metadata23.csv")
metadata <- link_dam_metadata(metadata, result_dir = DATA_DIR)
dt <- load_dam(metadata, date_format = "%d %b %y")

**Here is my metadata:**
region_id	DAM	file	start_datetime	stop_datetime	sex	genotype	replicate
1	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
2	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
3	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
4	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
5	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
6	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
7	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
8	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
9	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
10	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
11	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
12	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
13	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
14	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
15	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
16	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
17	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
18	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
19	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
20	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
21	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
22	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
23	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
24	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
25	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
26	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
27	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
28	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
29	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
30	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
31	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1
32	23	Monitor23.txt	2017-10-25 06:05:00	2017-10-30 10:27:00	male	A	1

My DAM data is attached
[Monitor23.txt](https://github.com/rethomics/damr/files/7039979/Monitor23.txt)

Thank you!

**Comment by katenevin21** [comment]
Never mind! I had written November as the 10th month in the metadata, instead of the 11th month.

**Comment by mantouyangmeng** [comment]
Hi, I'm trying to run the damr package, and when I run load_dam(metadata), I now keep getting "Error in find_dam_first_last_lines(path, start_datetime, stop_datetime,. No data in selected date range".
I've searched for ways to fix this (such as following the help provided in the error), but it still continues to report the error, and was wondering if you've encountered this problem?
