### ISSUE TITLE
query_dam2 dails when region_id is a character and not a integer.

### ISSUE THREAD

**Issue by pepelisu** [rethomics/damr#4]
I will suggest that query_dam2 should try to coerce the region_id to a integer, maybe using as.integer(). This will avoid this error: 
```
Error in sprintf("%02d|%s", region_id, experiment_id) : 
  invalid format '%02d'; use format %s for character objects
```

**Comment by qgeissmann** [comment]
I will work on that, thanks.
Can you send a reproducible example/traceback? 
Cheers

**Comment by pepelisu** [comment]
example:
```
query<-data.table(file="Monitor26.txt",start_datetime="2017-08-12 8:00:00",stop_datetime="2017-08-17 8:00:00", region_id="1")
```
I do not have traceback, the error was just that.

**Comment by qgeissmann** [comment]
I see, so you have a character region id (`"1"` -> `1`)... will think about implications of auto coercion.

**Comment by pepelisu** [comment]
I just did it like that because in the 'help' it says:
`region_id – the channel (between 1 and 32) in which the animal was in (e.g. "20"). `
I assumed that it has to be a character.

**Comment by qgeissmann** [comment]
ahah, ok. we should fix that then ;)

**Comment by qgeissmann** [comment]
changed the doc in "7f52d19922db38c9bcab76f754198e01dd8bb323"
