### ISSUE TITLE
How to exclude first two days of the new regime (DD) from analysis?

### ISSUE THREAD

**Issue by ko222uky** [rethomics/damr#40]
Hello,

I've worked through the tutorial with my own data, and everything went well.

Is there a simple way to exclude some of the first days in the new regime change?

Some key papers that I've read have excluded, for instance, the first two days in DD after transitioning from the LD to DD. This is to provide a period for the animals to acclimate. Trimming the data from the beginning and end of an experiment makes sense, and I can do that. I simply want to know of a simple way to exclude data in the middle of a trial (e.g., the first two days of DD).

Any help would be greatly appreciated. Thanks!

**Comment by qgeissmann** [comment]
hello, I am not sure I understand completely. you can arbitrarily subset any part of the data and analyse/plot the resulting data tables. I don't suppose you want to analyse non-contiguous data (e.g. removing the middle of a dataset). In almost all cases, I would advise to analyse, say, the baseline and, say, the treatment separately and comparing the statistics afterwards. E.g. : 
```R
dt_baseline <- dt[t< days(6)]
dt_treatment <- dt[t> days(8)]
```

**Comment by ko222uky** [comment]
Hello,

Thank you! And sorry, I realized that I had initially missed the line for subsetting the data, so my issue has been resolved.
